name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Deploy
      env:
        GARA_API_KEY: ${{ secrets.GARA_API_KEY }}
        GARA_CLIENT_ID: ${{ secrets.GARA_CLIENT_ID }}
        GA_VIEW_ID: ${{ secrets.GA_ViEW_ID }}
        PLAU_API_KEY: ${{ secrets.PLAU_API_KEY }}
      run: |
        echo PLAU_API_KEY

